### ISSUE TITLE
Fix bug and broken tests from VSMT updates

### ISSUE THREAD

**Issue by drewstone** [webb-tools/anon#63]
It seems we had taken out the larger test runner from the CI and so we didn't realise we had broken some tests (it's only testing the mixer client).

These tests fail.
```
test smt::tests::test_vsmt_prove_verif ... FAILED
test time_based_rewarding::tests::test_time_based_reward_gadget_verification ... FAILED
```

My investigation shows that `update` method on the `SMT` does not properly add leaves into leaf_indices afaik. So these modules try to unwrap that at some point and end up with an empty collection.

**Comment by filiplazovic** [comment]
`leaf_indices` are populated inside `add_leaves`, but it would be a good idea to do it inside `update` to make it future proof.
