### ISSUE TITLE
Nullifier tree

### ISSUE THREAD

**Issue by filiplazovic** [webb-tools/anon#8]
Instead of having a map of all nullifiers, we should use Merkle trees with leaves initialized as zero.

Step 1: Since the index of the leaf can be derived from the path, we can check if `get_index(path) == nullifier`.
Step 2: Verify that leaf at the provided path is 0: `verify(path, 0)`.
Step 3: Update the Nullifier tree at provided path with non-zero value: `update(path, 1)`.

If we keep track of every nullifier, it will take ~~`256 * ((2 ** 32) -1) = 137GB`~~ `(128 + 8) * (2 ** 32) = 73GB` (assuming map keys are 128 bits `blake2_128_concat`, and bool is 8 bits) per group tree, assuming the tree is 32 in height and is full.

~Nullifier tree will take 8kB.~ We are just saving the root hash so 256 bits.

**Comment by drewstone** [comment]
Hmm I kinda understand what you're getting at. Though I'm not sure this will work in practice. Our field is quite larger than 2^32, and nullifiers are expected to be random elements there. So this would require some decent amount of preprocessing to select nullifiers, likely more than simply generating a random value in the field to use as one.

You do bring up a good point about storage, though if we reach that storage limit it's definitely a double-edged sword. It will be a hugely populated tree! This is good to think about though.

**Comment by filiplazovic** [comment]
Since we initialize all the leaves as 0, the preprocessing is basically like the one you did previously: https://github.com/edgeware-builders/anon/blob/1f2a7f589b43d1cc58ecc3f9a486f16bdc9b36f4/pallets/merkle/src/lib.rs#L155-L173 just for 256 height (our field is 2 ** 256?). This can be done off-chain and stored into a constant

**Comment by filiplazovic** [comment]
I guess what I'm trying to say is that nullifier corresponds to an index of a leaf node in some sparse tree. We initialize all leaves as 0, and when a nullifier gets used, we update the leaf node at that index (we set it to 1).

**Comment by filiplazovic** [comment]
The downside is that users would need to sync their clients before verifying ZK proof, which could become a problem if a lot of people wants to do it at once

**Comment by filiplazovic** [comment]
This is also the case for the group tree, which can be solved by periodically saving the tree state users will prove against. The period should be long enough so all the nodes can sync before trying to submit the proof

**Comment by filiplazovic** [comment]
Closing until we find a solution to this:
> The downside is that users would need to sync their clients before verifying ZK proof, which could become a problem if a lot of people wants to do it at once

**Comment by filiplazovic** [comment]
We introduce a queue of nullifiers + their paths. Every time user submits a nullified, we check if it isn't in the tree using the method above, and we also check if it isn't in the queue.

Every `t` block we take nullifiers from the queue and insert it in the tree using the provided path. At each insert, we have to keep track of changes of the nodes on each level (this doesn't need to be in the storage) to be able to insert the next nullified.
This computation can be done inside `on_finalize` or using an off-chain worker.
In the end, we delete the nullifier queue and their paths

**Comment by filiplazovic** [comment]
@drewstone Let me know your solution

**Comment by drewstone** [comment]
The solution is to add nullifiers into yet another incrementally built merkle tree and then require users to provide non-membership proofs to this merkle tree. It would require the user to still get all the nullifiers in order to generate this proof. I think given the complexity of this I will still hold off from implementation and resort to storing nullifiers on chain. We can continue to spec this part out as an update/optimisation.
