### ISSUE TITLE
extract `gadgets`, `crypto-constants` and `wasm-utils` into a seprate crates/repos

### ISSUE THREAD

**Issue by shekohex** [webb-tools/anon#83]
We need to look into the way we need to manage this, as currently there will be a lot of shared code between the pallets, WASM, CLI, and in the future a Mobile App.

the following crates need to be extracted and live in their independent repos, so it makes it easy for other projects to pick things up and easily shared between all of our projects.

**Comment by drewstone** [comment]
Sure I'm not in a rush to do this as there could still be substantial changes to the gadgets we use and the elliptic curves/constants. It's ok for now imo.

**Comment by shekohex** [comment]
I don't like to complicate the dependency tree of the CLI for now, so I need to add the functionality similar to the wasm-utils to the CLI, which means I will have to pull the whole anon repo for just using the gadget, which is not good for compile-time, ..etc.

it would even be good to separate the work, so you could work independently from `anon` on the `gadgets` and so on..

**Comment by drewstone** [comment]
Sure but this is something we can handle later. We're not in a rush to optimise this yet since we're still in the development phase. I'd rather you use this package as is and we can tackle this later.

**Comment by drewstone** [comment]
We should use similar structure to webb.js for all wasm utilities / functions, so that they can be imported separately and have nice auto-versioning on new releases/changes.
