### ISSUE TITLE
max_leaves of group tree looks incorrect

### ISSUE THREAD

**Issue by drewstone** [webb-tools/anon#85]
```
impl GroupTree {
	pub fn new<T: Config>(depth: u8) -> Self {
		let init_edges: Vec<Data> = ZERO_TREE[0..depth as usize].iter().map(|x| Data::from(*x)).collect();
		let init_root = Data::from(ZERO_TREE[depth as usize]);
		Self {
			root_hash: init_root,
			leaf_count: 0,
			depth,
			max_leaves: u32::MAX >> (T::MaxTreeDepth::get() - depth),
			edge_nodes: init_edges,
		}
	}
}
```

If I have a tree of depth 3, then `max_leaves = 2^3`. Why don't we just do `2u32.pow(depth)`?

**Comment by filiplazovic** [comment]
To make sure there is no overflow:
`2^32` = `100000000000000000000000000000000` which is 33 bits
so we have to subtract one (`2^32 - 1`) to get:
`11111111111111111111111111111111` which is 32 bits

`u32::MAX >> (T::MaxTreeDepth::get() - depth)` does that
